import "server-only";

import { and, eq, max, sql } from "drizzle-orm";
import { z } from "zod";

import type { ActionResponse, ChangeMessage } from "@/lib/api-types";
import type { Db, Tx } from "@/lib/db";
import { batches, events, jobs, samples, type JobRow } from "@/lib/db/schema";
import {
  applyPlacement,
  applySampleAction,
  decideScan,
  MAX_NOTE_LENGTH,
  scanRejectEvent,
  scanRepeatEvent,
  type Action,
} from "@/lib/pipeline/actions";
import { destinationFor } from "@/lib/pipeline/destination";
import { parseLabel } from "@/lib/pipeline/labels";
import type { EventDraft, LogEvent, Sample } from "@/lib/pipeline/types";

import { HttpError } from "./errors";
import { sampleUpdate, toLogEvent, toSample } from "./rows";
import type { Participant } from "./tokens";

const id = z.string().uuid();

const actionSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.enum([
      "pull",
      "undo_pull",
      "label",
      "undo_label",
      "skip",
      "reopen",
      "return",
      "undo_return",
    ]),
    sampleId: id,
  }),
  z.object({
    type: z.literal("finish"),
    sampleId: id,
    note: z.string().max(MAX_NOTE_LENGTH).optional(),
  }),
  z.object({
    type: z.literal("undo_tube"),
    sampleId: id,
    tube: z.number().int().min(1).max(9),
  }),
  z.object({
    type: z.literal("note"),
    sampleId: id,
    text: z.string().max(MAX_NOTE_LENGTH),
  }),
  z.object({
    type: z.literal("scan"),
    label: z.string().max(200),
    currentSampleId: id.nullable(),
  }),
]);

export const actionRequestSchema = z.object({
  /** Generated by the device per action; a retry with the same id is not applied twice. */
  clientActionId: z.string().min(8).max(64),
  /** The device's clock when the person acted. */
  clientAt: z.iso.datetime().nullable().optional(),
  action: actionSchema,
});

export type ActionRequest = z.infer<typeof actionRequestSchema>;

/** Locks the job row: every logged change to a job happens one at a time. */
async function lockJob(tx: Tx, jobId: string): Promise<JobRow> {
  const [job] = await tx
    .select()
    .from(jobs)
    .where(eq(jobs.id, jobId))
    .for("update");
  if (!job) throw new HttpError(404, "no_job", "This job no longer exists.");
  return job;
}

async function serverNow(tx: Tx): Promise<string> {
  const result = await tx.execute<{ now: Date | string }>(
    sql`select clock_timestamp() as now`,
  );
  const now = result.rows[0]?.now;
  return new Date(now ?? Date.now()).toISOString();
}

async function loadSample(
  tx: Tx,
  jobId: string,
  sampleId: string,
): Promise<Sample> {
  const [row] = await tx
    .select()
    .from(samples)
    .where(and(eq(samples.jobId, jobId), eq(samples.id, sampleId)))
    .limit(1);
  if (!row)
    throw new HttpError(404, "no_sample", "That sample is not in this job.");
  return toSample(row);
}

async function boxNumberOf(
  tx: Tx,
  jobId: string,
  batchNumber: number,
): Promise<number> {
  const [batch] = await tx
    .select({ boxNumber: batches.boxNumber })
    .from(batches)
    .where(and(eq(batches.jobId, jobId), eq(batches.number, batchNumber)))
    .limit(1);
  return batch?.boxNumber ?? batchNumber;
}

/**
 * Appends events as the job's next version, saving changed samples with them.
 * Must run inside the transaction that locked the job.
 */
export async function commitChange(
  tx: Tx,
  job: JobRow,
  actor: { participantId: string | null; name: string; role: string | null },
  drafts: EventDraft[],
  changed: Sample[],
  meta: { clientActionId?: string | null; clientAt?: string | null } = {},
): Promise<{ version: number; events: LogEvent[] }> {
  const version = job.version + 1;
  for (const s of changed) {
    await tx.update(samples).set(sampleUpdate(s)).where(eq(samples.id, s.id));
  }
  const inserted = await tx
    .insert(events)
    .values(
      drafts.map((d, ord) => ({
        jobId: job.id,
        version,
        ord,
        clientAt: meta.clientAt ?? null,
        participantId: actor.participantId,
        actorName: actor.name,
        actorRole: actor.role,
        type: d.type,
        batchNumber: d.batchNumber ?? null,
        sampleId: d.sampleId ?? null,
        newId: d.newId ?? null,
        tube: d.tube ?? null,
        data: d.data ?? {},
        clientActionId: ord === 0 ? (meta.clientActionId ?? null) : null,
      })),
    )
    .returning();
  await tx.update(jobs).set({ version }).where(eq(jobs.id, job.id));
  return { version, events: inserted.map(toLogEvent) };
}

export async function performAction(
  db: Db,
  participant: Participant,
  request: ActionRequest,
): Promise<ActionResponse> {
  return db.transaction(async (tx) => {
    const job = await lockJob(tx, participant.jobId);

    const [previous] = await tx
      .select({ version: events.version })
      .from(events)
      .where(
        and(
          eq(events.jobId, job.id),
          eq(events.clientActionId, request.clientActionId),
        ),
      )
      .limit(1);
    if (previous) {
      return {
        ok: true,
        version: job.version,
        samples: [],
        events: [],
        duplicate: true,
      };
    }

    const now = await serverNow(tx);
    const actor = {
      participantId: participant.participantId,
      name: participant.name,
      role: participant.role,
    };
    const meta = {
      clientActionId: request.clientActionId,
      clientAt: request.clientAt ?? null,
    };
    const action = request.action as Action;

    if (action.type === "scan") {
      return scan(
        tx,
        job,
        participant,
        action.label,
        action.currentSampleId,
        now,
        actor,
        meta,
      );
    }

    const sample = await loadSample(tx, job.id, action.sampleId);
    let nextSkipRank = 1;
    if (action.type === "skip") {
      const [row] = await tx
        .select({ rank: max(samples.skipRank) })
        .from(samples)
        .where(
          and(
            eq(samples.jobId, job.id),
            eq(samples.batchNumber, sample.batchNumber),
          ),
        );
      nextSkipRank = (row?.rank ?? 0) + 1;
    }
    const result = applySampleAction(sample, action, {
      now,
      actor: participant.name,
      nextSkipRank,
    });
    if (!result.ok)
      throw new HttpError(409, result.error.code, result.error.message);
    const committed = await commitChange(
      tx,
      job,
      actor,
      result.events,
      [result.sample],
      meta,
    );
    return {
      ok: true,
      version: committed.version,
      samples: [result.sample],
      events: committed.events,
    };
  });
}

async function scan(
  tx: Tx,
  job: JobRow,
  participant: Participant,
  label: string,
  currentSampleId: string | null,
  now: string,
  actor: { participantId: string; name: string; role: string },
  meta: { clientActionId: string; clientAt: string | null },
): Promise<ActionResponse> {
  const parsed = parseLabel(label);
  let labelSample: Sample | null = null;
  if (parsed) {
    const [row] = await tx
      .select()
      .from(samples)
      .where(and(eq(samples.jobId, job.id), eq(samples.newId, parsed.newId)))
      .limit(1);
    labelSample = row ? toSample(row) : null;
  }
  const currentSample = currentSampleId
    ? await loadSample(tx, job.id, currentSampleId)
    : null;
  const decision = decideScan({
    label,
    parsed,
    labelSample,
    currentSample,
    batchNumber: participant.batchNumber,
    destCount: job.destSets.length,
  });

  if (decision.kind === "reject") {
    const draft = scanRejectEvent(
      label,
      decision,
      participant.batchNumber,
      currentSample,
      labelSample,
    );
    const committed = await commitChange(tx, job, actor, [draft], [], meta);
    return {
      ok: false,
      version: committed.version,
      samples: [],
      events: committed.events,
      scan: {
        kind: "reject",
        reason: decision.reason,
        message: decision.message,
      },
    };
  }

  const boxNumber = await boxNumberOf(tx, job.id, decision.sample.batchNumber);
  const destination = destinationFor(
    job.destSets,
    boxNumber,
    decision.sample.slot,
    decision.tube,
  );
  const tubeLabel = `${decision.sample.newId}-${decision.tube}`;

  if (decision.kind === "repeat") {
    const draft = scanRepeatEvent(
      decision.sample,
      decision.tube,
      job.destSets,
      boxNumber,
    );
    const committed = await commitChange(tx, job, actor, [draft], [], meta);
    return {
      ok: true,
      version: committed.version,
      samples: [],
      events: committed.events,
      scan: {
        kind: "repeat",
        label: tubeLabel,
        destination,
        sampleFinished: decision.sample.finishedAt !== null,
      },
    };
  }

  const placed = applyPlacement(decision.sample, decision.tube, {
    now,
    actor: participant.name,
    destSets: job.destSets,
    boxNumber,
  });
  const committed = await commitChange(
    tx,
    job,
    actor,
    placed.events,
    [placed.sample],
    meta,
  );
  return {
    ok: true,
    version: committed.version,
    samples: [placed.sample],
    events: committed.events,
    scan: {
      kind: "place",
      label: tubeLabel,
      destination,
      sampleFinished: placed.sample.finishedAt !== null,
    },
  };
}

export type { ActionResponse, ChangeMessage };
