import "server-only";

import { and, asc, eq, isNotNull, isNull, max, ne, sql } from "drizzle-orm";
import { z } from "zod";

import type { ActionResponse, ChangeMessage } from "@/lib/api-types";
import type { Db, Tx } from "@/lib/db";
import {
  batches,
  events,
  jobs,
  participants,
  samples,
  type JobRow,
} from "@/lib/db/schema";
import {
  applyLabelScan,
  applyPlacement,
  applySampleAction,
  decideLabelScan,
  decideScan,
  labelScanRepeatEvent,
  MAX_NOTE_LENGTH,
  scanRejectEvent,
  scanRepeatEvent,
  tubesPlacedBy,
  type Action,
  type ScanInput,
} from "@/lib/pipeline/actions";
import { destinationFor } from "@/lib/pipeline/destination";
import { parseLabel } from "@/lib/pipeline/labels";
import type { EventDraft, LogEvent, Sample } from "@/lib/pipeline/types";

import { HttpError } from "./errors";
import { isOnline } from "./jobs";
import { sampleUpdate, toLogEvent, toSample } from "./rows";
import { signParticipantToken, type Participant } from "./tokens";

const id = z.string().uuid();

const actionSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.enum([
      "pull",
      "undo_pull",
      "label",
      "undo_label",
      "skip",
      "reopen",
      "return",
      "undo_return",
    ]),
    sampleId: id,
  }),
  z.object({
    type: z.literal("finish"),
    sampleId: id,
    note: z.string().max(MAX_NOTE_LENGTH).optional(),
  }),
  z.object({
    type: z.literal("undo_tube"),
    sampleId: id,
    tube: z.number().int().min(1).max(9),
  }),
  z.object({
    type: z.literal("note"),
    sampleId: id,
    text: z.string().max(MAX_NOTE_LENGTH),
  }),
  z.object({
    type: z.enum(["scan", "label_scan"]),
    label: z.string().max(200),
    currentSampleId: id.nullable(),
  }),
]);

export const actionRequestSchema = z.object({
  /** Generated by the device per action; a retry with the same id is not applied twice. */
  clientActionId: z.string().min(8).max(64),
  /** The device's clock when the person acted. */
  clientAt: z.iso.datetime().nullable().optional(),
  action: actionSchema,
});

export type ActionRequest = z.infer<typeof actionRequestSchema>;

/** Locks the job row: every logged change to a job happens one at a time. */
async function lockJob(tx: Tx, jobId: string): Promise<JobRow> {
  const [job] = await tx
    .select()
    .from(jobs)
    .where(eq(jobs.id, jobId))
    .for("update");
  if (!job) throw new HttpError(404, "no_job", "This job no longer exists.");
  return job;
}

async function serverNow(tx: Tx): Promise<string> {
  const result = await tx.execute<{ now: Date | string }>(
    sql`select clock_timestamp() as now`,
  );
  const now = result.rows[0]?.now;
  return new Date(now ?? Date.now()).toISOString();
}

async function loadSample(
  tx: Tx,
  jobId: string,
  sampleId: string,
): Promise<Sample> {
  const [row] = await tx
    .select()
    .from(samples)
    .where(and(eq(samples.jobId, jobId), eq(samples.id, sampleId)))
    .limit(1);
  if (!row)
    throw new HttpError(404, "no_sample", "That sample is not in this job.");
  return toSample(row);
}

async function boxNumberOf(
  tx: Tx,
  jobId: string,
  batchNumber: number,
): Promise<number> {
  const [batch] = await tx
    .select({ boxNumber: batches.boxNumber })
    .from(batches)
    .where(and(eq(batches.jobId, jobId), eq(batches.number, batchNumber)))
    .limit(1);
  return batch?.boxNumber ?? batchNumber;
}

/**
 * Appends events as the job's next version, saving changed samples with them.
 * Must run inside the transaction that locked the job.
 */
export async function commitChange(
  tx: Tx,
  job: JobRow,
  actor: { participantId: string | null; name: string; role: string | null },
  drafts: EventDraft[],
  changed: Sample[],
  meta: { clientActionId?: string | null; clientAt?: string | null } = {},
): Promise<{ version: number; events: LogEvent[] }> {
  const version = job.version + 1;
  for (const s of changed) {
    await tx.update(samples).set(sampleUpdate(s)).where(eq(samples.id, s.id));
  }
  const inserted = await tx
    .insert(events)
    .values(
      drafts.map((d, ord) => ({
        jobId: job.id,
        version,
        ord,
        clientAt: meta.clientAt ?? null,
        participantId: actor.participantId,
        actorName: actor.name,
        actorRole: actor.role,
        type: d.type,
        batchNumber: d.batchNumber ?? null,
        sampleId: d.sampleId ?? null,
        newId: d.newId ?? null,
        tube: d.tube ?? null,
        data: d.data ?? {},
        clientActionId: ord === 0 ? (meta.clientActionId ?? null) : null,
      })),
    )
    .returning();
  await tx.update(jobs).set({ version }).where(eq(jobs.id, job.id));
  return { version, events: inserted.map(toLogEvent) };
}

export async function performAction(
  db: Db,
  participant: Participant,
  request: ActionRequest,
): Promise<ActionResponse> {
  return db.transaction(async (tx) => {
    const job = await lockJob(tx, participant.jobId);

    const [previous] = await tx
      .select({ type: events.type, data: events.data })
      .from(events)
      .where(
        and(
          eq(events.jobId, job.id),
          eq(events.clientActionId, request.clientActionId),
        ),
      )
      .limit(1);
    if (previous) {
      return {
        ok: true,
        version: job.version,
        samples: [],
        events: [],
        duplicate: true,
        // A retried scan that moved the station must still move it.
        ...(previous.type === "participant_moved"
          ? { moved: await sessionOn(participant, Number(previous.data.to)) }
          : {}),
      };
    }

    const now = await serverNow(tx);
    const actor = {
      participantId: participant.participantId,
      name: participant.name,
      role: participant.role,
    };
    const meta = {
      clientActionId: request.clientActionId,
      clientAt: request.clientAt ?? null,
    };
    const action = request.action as Action;

    if (action.type === "scan" || action.type === "label_scan") {
      const input = await loadScanInput(
        tx,
        job,
        participant,
        action.label,
        action.currentSampleId,
      );
      const context = { tx, job, participant, now, actor, meta };
      return action.type === "scan"
        ? scan(context, input)
        : labelScan(context, input);
    }

    const sample = await loadSample(tx, job.id, action.sampleId);
    let nextSkipRank = 1;
    if (action.type === "skip") {
      const [row] = await tx
        .select({ rank: max(samples.skipRank) })
        .from(samples)
        .where(
          and(
            eq(samples.jobId, job.id),
            eq(samples.batchNumber, sample.batchNumber),
          ),
        );
      nextSkipRank = (row?.rank ?? 0) + 1;
    }
    const result = applySampleAction(sample, action, {
      now,
      actor: participant.name,
      nextSkipRank,
    });
    if (!result.ok)
      throw new HttpError(409, result.error.code, result.error.message);
    const committed = await commitChange(
      tx,
      job,
      actor,
      result.events,
      [result.sample],
      meta,
    );
    return {
      ok: true,
      version: committed.version,
      samples: [result.sample],
      events: committed.events,
    };
  });
}

interface ScanContext {
  tx: Tx;
  job: JobRow;
  participant: Participant;
  now: string;
  actor: { participantId: string; name: string; role: string };
  meta: { clientActionId: string; clientAt: string | null };
}

/**
 * Looks up the sample a scanned label names and the station's current
 * sample, and for an Aliquoter's tube of another batch, whether the
 * station may move there (see decideScan).
 */
async function loadScanInput(
  tx: Tx,
  job: JobRow,
  participant: Participant,
  label: string,
  currentSampleId: string | null,
): Promise<ScanInput> {
  const parsed = parseLabel(label);
  let labelSample: Sample | null = null;
  if (parsed) {
    const [row] = await tx
      .select()
      .from(samples)
      .where(and(eq(samples.jobId, job.id), eq(samples.newId, parsed.newId)))
      .limit(1);
    labelSample = row ? toSample(row) : null;
  }
  const currentSample = currentSampleId
    ? await loadSample(tx, job.id, currentSampleId)
    : null;
  const input: ScanInput = {
    label,
    parsed,
    labelSample,
    currentSample,
    batchNumber: participant.batchNumber,
    destCount: job.destSets.length,
  };
  if (
    participant.role === "aliquoter" &&
    labelSample &&
    labelSample.batchNumber !== participant.batchNumber
  ) {
    // A source tube out on this batch is on the Aliquoter's screen.
    const [out] = await tx
      .select({ id: samples.id })
      .from(samples)
      .where(
        and(
          eq(samples.jobId, job.id),
          eq(samples.batchNumber, participant.batchNumber),
          isNotNull(samples.pulledAt),
          isNull(samples.finishedAt),
        ),
      )
      .limit(1);
    input.mayMove = !out;
    const [holder] = await tx
      .select({ name: participants.name })
      .from(participants)
      .where(
        and(
          eq(participants.jobId, job.id),
          eq(participants.role, "aliquoter"),
          eq(participants.batchNumber, labelSample.batchNumber),
          ne(participants.id, participant.participantId),
          isOnline,
        ),
      )
      .orderBy(asc(participants.queuedAt))
      .limit(1);
    input.heldBy = holder?.name ?? null;
  }
  return input;
}

/** A station's session on a batch: what its screen carries on with after a move. */
async function sessionOn(
  participant: Participant,
  batchNumber: number,
): Promise<NonNullable<ActionResponse["moved"]>> {
  const { participantId, name, role } = participant;
  return {
    token: await signParticipantToken({ ...participant, batchNumber }),
    me: { participantId, name, role, batchNumber },
  };
}

/** The aliquoter's scan: places a tube (and its sample's other pending ones), repeats a placed one, or rejects. */
async function scan(
  { tx, job, participant, now, actor, meta }: ScanContext,
  input: ScanInput,
): Promise<ActionResponse> {
  const { label, currentSample, labelSample } = input;
  const decision = decideScan(input);

  if (decision.kind === "reject") {
    const draft = scanRejectEvent(
      label,
      decision,
      participant.batchNumber,
      currentSample,
      labelSample,
    );
    const committed = await commitChange(tx, job, actor, [draft], [], meta);
    return {
      ok: false,
      version: committed.version,
      samples: [],
      events: committed.events,
      scan: {
        kind: "reject",
        reason: decision.reason,
        message: decision.message,
      },
    };
  }

  const boxNumber = await boxNumberOf(tx, job.id, decision.sample.batchNumber);
  const destination = destinationFor(
    job.destSets,
    boxNumber,
    decision.sample.slot,
    decision.tube,
  );
  const tubeLabel = `${decision.sample.newId}-${decision.tube}`;

  if (decision.kind === "repeat") {
    const draft = scanRepeatEvent(
      decision.sample,
      decision.tube,
      job.destSets,
      boxNumber,
    );
    const committed = await commitChange(tx, job, actor, [draft], [], meta);
    return {
      ok: true,
      version: committed.version,
      samples: [],
      events: committed.events,
      scan: {
        kind: "repeat",
        label: tubeLabel,
        destination,
        tubes: [decision.tube],
        sampleFinished: decision.sample.finishedAt !== null,
      },
    };
  }

  // A tube of another batch takes the station there first. Like joining
  // that batch, it takes its place in line for the role from now.
  const moveTo = decision.moveTo;
  const moved: EventDraft[] = [];
  if (moveTo !== undefined) {
    await tx
      .update(participants)
      .set({ batchNumber: moveTo, queuedAt: sql`clock_timestamp()` })
      .where(eq(participants.id, participant.participantId));
    moved.push({
      type: "participant_moved",
      batchNumber: participant.batchNumber,
      data: { to: moveTo, label: tubeLabel },
    });
  }

  const placed = applyPlacement(decision.sample, decision.tube, {
    now,
    actor: participant.name,
    destSets: job.destSets,
    boxNumber,
  });
  const committed = await commitChange(
    tx,
    job,
    actor,
    [...moved, ...placed.events],
    [placed.sample],
    meta,
  );
  return {
    ok: true,
    version: committed.version,
    samples: [placed.sample],
    events: committed.events,
    scan: {
      kind: "place",
      label: tubeLabel,
      destination,
      tubes: tubesPlacedBy(decision.sample, decision.tube),
      sampleFinished: placed.sample.finishedAt !== null,
    },
    ...(moveTo !== undefined
      ? { moved: await sessionOn(participant, moveTo) }
      : {}),
  };
}

export type { ActionResponse, ChangeMessage };

/** The labeler's scan: records a checked label; the sample's last one marks it labeled. */
async function labelScan(
  { tx, job, participant, now, actor, meta }: ScanContext,
  input: ScanInput,
): Promise<ActionResponse> {
  const { label, currentSample, labelSample } = input;
  const decision = decideLabelScan(input);

  if (decision.kind === "reject") {
    const draft = scanRejectEvent(
      label,
      decision,
      participant.batchNumber,
      currentSample,
      labelSample,
      "label_scan_rejected",
    );
    const committed = await commitChange(tx, job, actor, [draft], [], meta);
    return {
      ok: false,
      version: committed.version,
      samples: [],
      events: committed.events,
      labelScan: {
        kind: "reject",
        reason: decision.reason,
        message: decision.message,
      },
    };
  }

  const { sample, tube } = decision;
  const outcome = {
    label: `${sample.newId}-${tube}`,
    tube,
    set: job.destSets[tube - 1] ?? `Set ${tube}`,
  };

  if (decision.kind === "repeat") {
    const committed = await commitChange(
      tx,
      job,
      actor,
      [labelScanRepeatEvent(sample, tube)],
      [],
      meta,
    );
    return {
      ok: true,
      version: committed.version,
      samples: [],
      events: committed.events,
      labelScan: {
        kind: "repeat",
        ...outcome,
        sampleLabeled: sample.labeledAt !== null,
      },
    };
  }

  const recorded = applyLabelScan(sample, tube, {
    now,
    actor: participant.name,
  });
  const committed = await commitChange(
    tx,
    job,
    actor,
    recorded.events,
    [recorded.sample],
    meta,
  );
  return {
    ok: true,
    version: committed.version,
    samples: [recorded.sample],
    events: committed.events,
    labelScan: {
      kind: "record",
      ...outcome,
      sampleLabeled: recorded.sample.labeledAt !== null,
    },
  };
}
