/**
 * Prints the SQL that records one admin invite, and the invite's link.
 * This is how the first admin gets in, and the way back in if every passkey
 * is lost. After that, admins make invite links on the admin page.
 *
 *   npm run --silent admin-invite-sql -- --origin https://aliquot.example.org > invite.sql
 *   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f invite.sql
 *
 * The link is printed to the terminal, not into the SQL: the SQL holds only
 * the token's hash. The link works once, and expires --minutes (default 10)
 * after the SQL is applied.
 */
import { parseArgs } from "node:util";

import { drizzle } from "drizzle-orm/node-postgres";

import { INVITE_MINUTES, invitePath, newInvite } from "@/lib/admin/invites";
import * as schema from "@/lib/db/schema";
import { renderStatement } from "@/lib/jobs/render-sql";

function main() {
  const { values } = parseArgs({
    options: {
      origin: { type: "string" },
      minutes: { type: "string", default: String(INVITE_MINUTES) },
    },
  });
  const minutes = Number(values.minutes);
  if (!values.origin || !Number.isInteger(minutes) || minutes < 1) {
    console.error(
      "Usage: npm run --silent admin-invite-sql -- --origin https://<the app's address> [--minutes 10]",
    );
    process.exit(2);
  }
  const origin = new URL(values.origin).origin;

  const { token, insert } = newInvite(drizzle.mock({ schema }), {
    createdBy: null,
    minutes,
  });
  const query = insert.toSQL();
  process.stdout.write(
    [
      "-- One admin invite. Generated by scripts/admin-invite-sql.ts.",
      `${renderStatement(query.sql, query.params)};`,
      "",
    ].join("\n"),
  );
  console.error(
    `Invite link, valid for ${minutes} minutes once the SQL is applied:\n${origin}${invitePath(token)}`,
  );
}

main();
