/**
 * Turns an aliquot workbook into a standalone SQL file that creates one job,
 * for seeding a database without going through the web UI.
 *
 *   npm run seed-sql -- <workbook.xlsx> --name "Aliquot 2026" --by "Jerry" > job.seed.sql
 *   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f job.seed.sql
 *
 * The output contains the samples' IDs and storage positions. Keep it out of
 * the repository (*.seed.sql is gitignored).
 */
import { readFileSync } from "node:fs";
import { basename } from "node:path";
import { parseArgs } from "node:util";

import { drizzle } from "drizzle-orm/node-postgres";

import * as schema from "@/lib/db/schema";
import {
  formatJobCode,
  generateJobCode,
  isValidJobCode,
  normalizeJobCode,
} from "@/lib/job-code";
import { buildJobInserts } from "@/lib/jobs/create";
import { renderStatement } from "@/lib/jobs/render-sql";
import { summarizeBatch } from "@/lib/workbook/model";
import { parseWorkbook } from "@/lib/workbook/parse";

async function main() {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      name: { type: "string" },
      by: { type: "string" },
      code: { type: "string" },
    },
  });
  const file = positionals[0];
  if (!file || !values.name || !values.by) {
    console.error(
      'Usage: npm run seed-sql -- <workbook.xlsx> --name "<job name>" --by "<your name>" [--code ABCDEFGH]',
    );
    process.exit(2);
  }
  const code = values.code ? normalizeJobCode(values.code) : generateJobCode();
  if (!isValidJobCode(code)) {
    console.error(
      `Invalid job code "${values.code}": 8 letters, no I, L or O.`,
    );
    process.exit(2);
  }

  const buf = readFileSync(file);
  const parsed = await parseWorkbook(
    buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  );
  for (const w of parsed.warnings) console.error(`warning: ${w}`);
  if (!parsed.workbook) {
    for (const e of parsed.errors) console.error(`error: ${e}`);
    process.exit(1);
  }

  const db = drizzle.mock({ schema });
  const { statements } = buildJobInserts(db, {
    code,
    name: values.name,
    createdBy: values.by,
    sourceFilename: basename(file),
    workbook: parsed.workbook,
  });

  const summaries = parsed.workbook.batches.map(summarizeBatch);
  const total = summaries.reduce((n, b) => n + b.samples, 0);
  const lines = [
    `-- Job "${values.name.replace(/\n/g, " ")}" — code ${formatJobCode(code)}`,
    `-- From ${basename(file)}: ${summaries.length} batches, ${total} samples.`,
    `-- Destination sets: ${parsed.workbook.destSets.join(", ")}.`,
    "-- Generated by scripts/workbook-to-seed-sql.ts. Contains sample data: do not commit.",
    "",
    "BEGIN;",
    ...statements.map((s) => {
      const q = s.toSQL();
      return `${renderStatement(q.sql, q.params)};`;
    }),
    "COMMIT;",
    "",
  ];
  process.stdout.write(lines.join("\n"));
  console.error(
    `Job code: ${formatJobCode(code)} (${summaries.length} batches, ${total} samples)`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
